---
# Site Settings
title: $$DevOps \subset CS$$
email: /dev/null
description: >-
  Ramblings of a former BOFH turned DevOps "engineer". On a continuous 
  quest to find the correlation of CS and systems administration work
  in order to help my understanding of both.
baseurl: ""
url: "https://beastie29a.github.io"
github_username:  beastie29a
linkedin_username: robert-c-8406b35

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - .stash

# plugins:
#   - jekyll-katex

markdown: kramdown
kramdown:
    math_engine: katex